# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-11 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('out_trade_no', models.CharField(max_length=64, unique=True, verbose_name='美多商城编号')),
                ('trade_no', models.CharField(max_length=64, unique=True, verbose_name='支付宝流水号')),
            ],
            options={
                'db_table': 'tb_payment',
            },
        ),
    ]
